version: '3'
services:
  app:
    image: sasuk1/express-sqlite-app
    container_name: express-sqlite-app
    volumes:
        -  ./mydatabase.db:/usr/src/app/mydatabase.db
    ports:
        - "3001:3000"